CREATE TABLE ascend_climbs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP DEFAULT now(),
    location TEXT NOT NULL,
    climb_name TEXT NOT NULL,
    climb_grade TEXT NOT NULL,
    user_status TEXT NOT NULL,
    image TEXT,
    user_id INTEGER
        REFERENCES ascend_users(id) ON DELETE CASCADE NOT NULL
);
