CREATE TABLE ascend_climbs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TIMESTAMP DEFAULT now(),
    location TEXT,
    climb_name TEXT,
    climb_grade INTEGER,
    user_status TEXT,
    image TEXT,
    user_id INTEGER
        REFERENCES ascend_users(id) ON DELETE CASCADE NOT NULL
);
